default:
  image: node:14.17.5
  cache:
    paths:
      - node_modules/
  before_script:
    - yarn install

test:
  stage: test
  script:
    - yarn lint
    - yarn check-format
    - yarn test

build:
  stage: build
  script:
    - yarn build
# For gitlab ci deployment
# deploy-staging:
#   stage: deploy
#   script:
#     - apt-get install git openssh-client -y
#     - eval $(ssh-agent -s)
#     - ssh-add <(echo "$SSH_PRIVATE_KEY")
#     - mkdir -p ~/.ssh
#     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
#     - npx pm2 deploy ecosystem.config.js staging setup --force 2>&1 || true
#     - npx pm2 deploy ecosystem.config.js staging --force
#   only:
#     - staging

# deploy-production:
#   stage: deploy
#   script:
#     - apt-get install git openssh-client -y
#     - eval $(ssh-agent -s)
#     - ssh-add <(echo "$SSH_PRIVATE_KEY")
#     - mkdir -p ~/.ssh
#     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
#     - npx pm2 deploy ecosystem.config.js production setup --force 2>&1 || true
#     - npx pm2 deploy ecosystem.config.js production --force
#   only:
#     - master
